// pi-mobile/src/features/chat/components/MessageList.svelte
<script lang="ts">
  import { onMount, tick } from "svelte";
  import { ArrowDown } from "@lucide/svelte";
  import { chatLogState } from "@/features/chat/model/chat-log.state.svelte";
  import UserMessageView from "@/features/chat/components/UserMessage.svelte";
  import AssistantMessageView from "@/features/chat/components/AssistantMessage.svelte";
  import ToolCallView from "@/features/chat/components/ToolCall.svelte";
  import PermissionGate from "@/features/chat/components/PermissionGate.svelte";

  const STICK_THRESHOLD_PX = 64;

  let scroller = $state<HTMLDivElement | null>(null);
  let stuckToBottom = $state(true);
  let hasNewActivity = $state(false);
  let lastActivityVersion = $state(chatLogState.activityVersion);

  function distanceFromBottom(): number {
    if (!scroller) return 0;
    return scroller.scrollHeight - scroller.scrollTop - scroller.clientHeight;
  }

  function scrollToLatest(behavior: ScrollBehavior = "smooth"): void {
    if (!scroller) return;
    scroller.scrollTo({ top: scroller.scrollHeight, behavior });
    stuckToBottom = true;
    hasNewActivity = false;
  }

  function onScroll(): void {
    const stuck = distanceFromBottom() < STICK_THRESHOLD_PX;
    stuckToBottom = stuck;
    if (stuck) hasNewActivity = false;
  }

  onMount(() => {
    scrollToLatest("auto");
  });

  $effect(() => {
    const version = chatLogState.activityVersion;
    if (version === lastActivityVersion) return;
    lastActivityVersion = version;
    void tick().then(() => {
      if (stuckToBottom) scrollToLatest("auto");
      else hasNewActivity = true;
    });
  });
</script>

<div class="relative min-h-0 flex-1">
  <div bind:this={scroller} onscroll={onScroll} class="scroll-momentum h-full overflow-y-auto py-2" style="padding-bottom: 0.5rem">
    {#each chatLogState.entries as entry (entry.id)}
      {#if entry.kind === "user"}
        <UserMessageView msg={entry} />
      {:else if entry.kind === "assistant"}
        <AssistantMessageView msg={entry} />
      {:else if entry.kind === "tool_call"}
        <ToolCallView msg={entry} />
      {:else if entry.kind === "permission"}
        <PermissionGate req={entry} />
      {/if}
    {/each}
  </div>

  {#if !stuckToBottom}
    <button
      type="button"
      onclick={() => scrollToLatest()}
      class="absolute right-3 z-30 flex items-center gap-1.5 rounded-full border border-[color:var(--color-border-strong)] bg-[color:var(--color-surface)]/95 px-3 py-1.5 text-[11px] text-[color:var(--color-fg)] shadow-lg backdrop-blur-md active:bg-[color:var(--color-surface-2)]"
      style="bottom: 0.75rem"
      aria-label="Scroll to latest message"
    >
      <ArrowDown class="size-3.5" />
      <span>{hasNewActivity ? "new" : "latest"}</span>
    </button>
  {/if}
</div>

// pi-mobile/src/features/chat/components/MessageList.tsx
import {
  For,
  Show,
  createEffect,
  createSignal,
  on,
  onCleanup,
  onMount,
} from "solid-js";
import { ArrowDown } from "lucide-solid";
import { activityVersion, entries } from "@/stores/sessions";
import UserMessageView from "./UserMessage";
import AssistantMessageView from "./AssistantMessage";
import ToolCallView from "./ToolCall";
import PermissionGate from "./PermissionGate";

const STICK_THRESHOLD_PX = 64;

export default function MessageList() {
  let scroller!: HTMLDivElement;
  const [stuckToBottom, setStuckToBottom] = createSignal(true);
  const [hasNewActivity, setHasNewActivity] = createSignal(false);

  function distanceFromBottom(): number {
    return scroller.scrollHeight - scroller.scrollTop - scroller.clientHeight;
  }

  function scrollToLatest(behavior: ScrollBehavior = "smooth") {
    scroller.scrollTo({ top: scroller.scrollHeight, behavior });
    setStuckToBottom(true);
    setHasNewActivity(false);
  }

  function onScroll() {
    const stuck = distanceFromBottom() < STICK_THRESHOLD_PX;
    setStuckToBottom(stuck);
    if (stuck) setHasNewActivity(false);
  }

  onMount(() => {
    scroller.addEventListener("scroll", onScroll, { passive: true });
    scrollToLatest("auto");
  });
  onCleanup(() => scroller?.removeEventListener("scroll", onScroll));

  createEffect(
    on(
      activityVersion,
      () => {
        if (stuckToBottom()) {
          scrollToLatest("auto");
        } else {
          setHasNewActivity(true);
        }
      },
      { defer: true },
    ),
  );

  return (
    <div class="relative min-h-0 flex-1">
      <div
        ref={scroller}
        class="scroll-momentum h-full overflow-y-auto py-2"
        style={{ "padding-bottom": "0.5rem" }}
      >
        <For each={entries()}>
          {(entry) => {
            switch (entry.kind) {
              case "user":
                return <UserMessageView msg={entry} />;
              case "assistant":
                return <AssistantMessageView msg={entry} />;
              case "tool_call":
                return <ToolCallView msg={entry} />;
              case "permission":
                return <PermissionGate req={entry} />;
            }
          }}
        </For>

      </div>

      <Show when={!stuckToBottom()}>
        <button
          type="button"
          onClick={() => scrollToLatest()}
          class="absolute right-3 z-30 flex items-center gap-1.5 rounded-full border border-[color:var(--color-border-strong)] bg-[color:var(--color-surface)]/95 px-3 py-1.5 text-[11px] text-[color:var(--color-fg)] shadow-lg backdrop-blur-md active:bg-[color:var(--color-surface-2)]"
          style={{ bottom: "0.75rem" }}
          aria-label="Scroll to latest message"
        >
          <ArrowDown size={13} />
          <span>{hasNewActivity() ? "new" : "latest"}</span>
        </button>
      </Show>
    </div>
  );
}
