// pico/src/features/chat/components/ToolCall.svelte
<script lang="ts">
  import { Check, FileText, Loader2, Pencil, PlusSquare, Terminal, X } from "@lucide/svelte";
  import type { ToolCallMessage } from "@pico/protocol";
  import { shortPath } from "@/shared/lib/format";
  import EditDiff from "@/features/chat/components/EditDiff.svelte";
  import ToolResult from "@/features/chat/components/ToolResult.svelte";

  let { msg }: { msg: ToolCallMessage } = $props();
  // svelte-ignore state_referenced_locally
  let open = $state(msg.toolKind === "builtin" && msg.tool === "edit");

  $effect(() => {
    if (msg.status === "running" && (msg.result || msg.resultContent || msg.details !== undefined)) open = true;
  });

  const label = $derived(msg.toolKind === "builtin" ? msg.tool : msg.tool);
  const summary = $derived.by(() => {
    if (msg.toolKind === "custom") return JSON.stringify(msg.args);
    switch (msg.tool) {
      case "read":
      case "write":
      case "edit":
        return shortPath(msg.args.path, 2);
      case "bash":
        return msg.args.command;
    }
  });
</script>

<div class="px-3 py-1">
  <button
    type="button"
    onclick={() => (open = !open)}
    class="group flex w-full items-center gap-2 rounded-[var(--radius-sm)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-2.5 py-1.5 text-left active:bg-[color:var(--color-surface-2)]"
  >
    <span class="flex h-4 w-4 items-center justify-center text-[color:var(--color-fg-muted)]">
      {#if msg.toolKind === "builtin" && msg.tool === "read"}
        <FileText class="size-3" />
      {:else if msg.toolKind === "builtin" && msg.tool === "write"}
        <PlusSquare class="size-3" />
      {:else if msg.toolKind === "builtin" && msg.tool === "edit"}
        <Pencil class="size-3" />
      {:else}
        <Terminal class="size-3" />
      {/if}
    </span>

    <span class="type-label uppercase tracking-[0.08em] text-[color:var(--color-fg-faint)]">{label}</span>
    <span class="type-meta min-w-0 flex-1 truncate text-[color:var(--color-fg)]">{summary}</span>

    {#if msg.status === "running"}
      <Loader2 class="size-3 animate-spin text-[color:var(--color-accent)]" />
    {:else if msg.status === "ok"}
      <Check class="size-3 text-[color:var(--color-fg-faint)]" />
      {#if msg.durationMs !== undefined}
        <span class="type-label uppercase tracking-[0.08em] text-[color:var(--color-fg-faint)] tabular-nums">{msg.durationMs}ms</span>
      {/if}
    {:else if msg.status === "error"}
      <X class="size-3 text-[color:var(--color-danger)]" />
    {/if}
  </button>

  {#if open}
    {#if msg.toolKind === "builtin" && msg.tool === "edit"}
      <div class="mt-1">
        <EditDiff args={msg.args} />
      </div>
    {:else}
      {#if msg.toolKind === "custom"}
        <!-- A custom tool's args have no known shape, so render them as formatted JSON. -->
        <pre
          class="mt-1 max-h-60 overflow-y-auto whitespace-pre-wrap break-words rounded-[var(--radius-sm)] border border-[color:var(--color-border)] bg-[color:var(--color-code-bg)] px-3 py-2 type-code text-[color:var(--color-code-fg)]">{JSON.stringify(
            msg.args,
            null,
            2,
          )}</pre>
      {/if}
      {#if msg.result || msg.resultContent || msg.details !== undefined || (msg.toolKind === "builtin" && msg.tool === "write" && msg.args.content.length > 0)}
        <ToolResult {msg} />
      {/if}
    {/if}
  {/if}
</div>

// pi-mobile/src/features/chat/components/ToolCall.tsx
import { createSignal, Show, type JSX } from "solid-js";
import {
  FileText,
  Pencil,
  PlusSquare,
  Terminal,
  Check,
  X,
  Loader2,
} from "lucide-solid";
import type { BuiltinToolName, ToolCallMessage } from "@pi-mobile/protocol";
import { shortPath } from "@/lib/format";
import EditDiff from "./EditDiff";
import ToolResult from "./ToolResult";

const ICONS: Record<BuiltinToolName, (p: { size: number }) => JSX.Element> = {
  read: (p) => <FileText size={p.size} />,
  write: (p) => <PlusSquare size={p.size} />,
  edit: (p) => <Pencil size={p.size} />,
  bash: (p) => <Terminal size={p.size} />,
};

function summary(msg: ToolCallMessage): string {
  if (msg.toolKind === "custom") return JSON.stringify(msg.args);

  switch (msg.tool) {
    case "read":
    case "write":
    case "edit":
      return shortPath(msg.args.path, 2);
    case "bash":
      return msg.args.command;
  }
}

function ExpandedView(props: { msg: ToolCallMessage }) {
  if (props.msg.toolKind === "builtin" && props.msg.tool === "edit") {
    return (
      <div class="mt-1">
        <EditDiff args={props.msg.args} />
      </div>
    );
  }

  const hasContent = () =>
    !!props.msg.result ||
    (props.msg.toolKind === "builtin" &&
      props.msg.tool === "write" &&
      props.msg.args.content.length > 0);

  return (
    <Show when={hasContent()}>
      <ToolResult msg={props.msg} />
    </Show>
  );
}

export default function ToolCallView(props: {
  msg: ToolCallMessage;
}) {
  const [open, setOpen] = createSignal(
    props.msg.toolKind === "builtin" && props.msg.tool === "edit",
  );
  const Icon =
    props.msg.toolKind === "builtin" ? ICONS[props.msg.tool] : Terminal;

  return (
    <div class="px-3 py-1">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        class="group flex w-full items-center gap-2 rounded-[var(--radius-sm)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-2.5 py-1.5 text-left active:bg-[color:var(--color-surface-2)]"
      >
        <span class="flex h-4 w-4 items-center justify-center text-[color:var(--color-fg-muted)]">
          <Icon size={12} />
        </span>

        <span class="text-[10px] uppercase tracking-[0.08em] text-[color:var(--color-fg-faint)]">
          {props.msg.tool}
        </span>

        <span class="min-w-0 flex-1 truncate text-[12px] text-[color:var(--color-fg)]">
          {summary(props.msg)}
        </span>

        <Show when={props.msg.status === "running"}>
          <Loader2
            size={12}
            class="pulse-accent text-[color:var(--color-accent)]"
            style={{ animation: "spin 1s linear infinite" }}
          />
        </Show>
        <Show when={props.msg.status === "ok"}>
          <Check size={12} class="text-[color:var(--color-fg-faint)]" />
          <Show when={props.msg.durationMs !== undefined}>
            <span class="text-[10px] text-[color:var(--color-fg-faint)] tabular-nums">
              {props.msg.durationMs}ms
            </span>
          </Show>
        </Show>
        <Show when={props.msg.status === "error"}>
          <X size={12} class="text-[color:var(--color-danger)]" />
        </Show>
      </button>

      <Show when={open()}>
        <ExpandedView msg={props.msg} />
      </Show>
    </div>
  );
}
