// pi-mobile/src/features/sessions/components/NewSessionSheet.tsx
import { createSignal, Show, type JSX } from "solid-js";
import { Folder, GitBranch, Plus } from "lucide-solid";
import BottomSheet from "@/components/BottomSheet";
import { Button } from "@/components/ui/button";
import { TextField, TextFieldInput, TextFieldLabel } from "@/components/ui/text-field";
import CwdPicker from "./CwdPicker";

interface Props {
  open: boolean;
  onCancel: () => void;
  onCreate: (opts: { cwd: string; title: string; branch?: string }) => void;
  creating?: boolean;
}

function basename(path: string): string {
  const trimmed = path.replace(/\/+$/, "");
  const idx = trimmed.lastIndexOf("/");
  return idx >= 0 ? trimmed.slice(idx + 1) : trimmed;
}

export default function NewSessionSheet(props: Props) {
  const [cwd, setCwd] = createSignal<string | null>(null);
  const [title, setTitle] = createSignal("");
  const [branch, setBranch] = createSignal("");
  const [pickerOpen, setPickerOpen] = createSignal(false);
  const [titleTouched, setTitleTouched] = createSignal(false);

  const effectiveTitle = () => {
    const t = title().trim();
    if (t.length > 0) return t;
    const c = cwd();
    return c ? basename(c) : "";
  };

  const canCreate = () => cwd() !== null && cwd()!.length > 0 && !props.creating;

  function handleCreate() {
    const c = cwd();
    if (!c) return;
    props.onCreate({
      cwd: c,
      title: effectiveTitle(),
      branch: branch().trim() || undefined,
    });
  }

  return (
    <Show when={props.open}>
      <BottomSheet open title="new session" onClose={props.onCancel} maxHeightClass="max-h-[92dvh]">
        <div class="flex-1 space-y-3 overflow-y-auto px-3 pb-3">
          <Field label="cwd">
            <button
              type="button"
              onClick={() => setPickerOpen(true)}
              class="flex w-full items-center gap-2 rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-3 py-2.5 text-left active:bg-[color:var(--color-surface-2)]"
            >
              <Folder size={13} class="shrink-0 text-[color:var(--color-fg-muted)]" />
              <Show
                when={cwd()}
                fallback={
                  <span class="text-[12.5px] text-[color:var(--color-fg-faint)]">
                    choose a directory…
                  </span>
                }
              >
                <span class="min-w-0 flex-1 truncate text-[12.5px]">{cwd()}</span>
              </Show>
            </button>
          </Field>

          <TextField>
            <TextFieldLabel>title</TextFieldLabel>
            <TextFieldInput
              type="text"
              value={title()}
              onInput={(e) => {
                setTitle(e.currentTarget.value);
                if (!titleTouched()) setTitleTouched(true);
              }}
              placeholder={cwd() ? basename(cwd()!) : "session title"}
              class="py-2.5"
            />
          </TextField>

          <Field label="branch (optional)">
            <div class="flex items-center gap-2 rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-3 py-0.5 focus-within:border-[color:var(--color-border-strong)]">
              <GitBranch size={12} class="shrink-0 text-[color:var(--color-fg-muted)]" />
              <TextFieldInput
                type="text"
                value={branch()}
                onInput={(e) => setBranch(e.currentTarget.value)}
                placeholder="main"
                class="border-0 bg-transparent px-0 py-2 focus:border-0 focus-visible:border-0"
              />
            </div>
          </Field>
        </div>

        <div class="px-3 pt-2">
          <Button
            type="button"
            variant="accent"
            size="default"
            onClick={handleCreate}
            disabled={!canCreate()}
            class="w-full"
          >
            <Plus size={14} strokeWidth={2.5} />
            {props.creating ? "creating…" : "create session"}
          </Button>
        </div>

        <Show when={pickerOpen()}>
          <CwdPicker
            initial={cwd() ?? undefined}
            onSelect={(p) => {
              setCwd(p);
              setPickerOpen(false);
            }}
            onCancel={() => setPickerOpen(false)}
          />
        </Show>
      </BottomSheet>
    </Show>
  );
}

function Field(props: { label: string; children: JSX.Element }) {
  return (
    <label class="block">
      <div class="label mb-1.5">{props.label}</div>
      {props.children}
    </label>
  );
}

// pico/src/features/sessions/components/NewSessionSheet.svelte
<script lang="ts">
  import { ChevronLeft, Folder, Plus } from "@lucide/svelte";
  import CwdPicker from "@/features/sessions/components/CwdPicker.svelte";
  import type { HostProfile } from "@/features/hosts/host-registry.state.svelte";
  import ActionRow from "@/shared/components/ActionRow.svelte";
  import { Button } from "@/shared/ui/button";
  import { Input } from "@/shared/ui/input";
  import * as Sheet from "@/shared/ui/sheet";

  let {
    open = $bindable(false),
    hosts,
    defaultHostId,
    creating = false,
    onCreate,
  }: {
    open: boolean;
    hosts: readonly HostProfile[];
    defaultHostId: string | null;
    creating?: boolean;
    onCreate: (opts: { hostId: string; cwd: string; title: string }) => void;
  } = $props();

  let hostId = $state<string | null>(null);
  let cwd = $state<string | undefined>();
  let title = $state("");
  let pickerOpen = $state(false);

  const effectiveTitle = $derived.by(() => {
    const trimmed = title.trim();
    if (trimmed.length > 0) return trimmed;
    return cwd ? basename(cwd) : "";
  });

  const canCreate = $derived(!!hostId && !!cwd && !creating);

  $effect(() => {
    if (!hostId || !hosts.some((host) => host.id === hostId)) hostId = defaultHostId;
  });

  function chooseHost(nextHostId: string): void {
    if (nextHostId === hostId) return;
    hostId = nextHostId;
    cwd = undefined;
  }

  function handleCreate(): void {
    if (!hostId || !cwd || !canCreate) return;
    onCreate({ hostId, cwd, title: effectiveTitle });
  }

  function basename(path: string): string {
    const trimmed = path.replace(/\/+$/, "");
    const index = trimmed.lastIndexOf("/");
    return index >= 0 ? trimmed.slice(index + 1) : trimmed;
  }
</script>

<Sheet.Root bind:open>
  <Sheet.BottomContent class="max-h-[92dvh]">
    <Sheet.Header class="hairline-b flex-row items-center gap-1 space-y-0 px-2 py-2 pr-12 text-left">
      {#if pickerOpen}
        <Button type="button" variant="ghost" size="icon" onclick={() => (pickerOpen = false)} aria-label="Back">
          <ChevronLeft class="size-4" />
        </Button>
      {:else}
        <div class="h-9 w-9"></div>
      {/if}
      <Sheet.Title class="type-title min-w-0 flex-1 px-1 font-medium">
        {pickerOpen ? "choose directory" : "new session"}
      </Sheet.Title>
    </Sheet.Header>

    {#if pickerOpen}
      {#if hostId}
        <CwdPicker
        {hostId}
        initial={cwd}
        onSelect={(path) => {
          cwd = path;
          pickerOpen = false;
        }}
        />
      {/if}
    {:else}
      <div class="flex-1 space-y-3 overflow-y-auto px-3 pb-3">
        <div>
          <div class="label mb-1.5">host</div>
          <div class="overflow-hidden rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)]">
            {#each hosts as host (host.id)}
              <ActionRow disabled={creating} onclick={() => chooseHost(host.id)} class="gap-3 active:bg-[color:var(--color-surface-2)]">
                <span class="min-w-0 flex-1">
                  <span class="type-copy block truncate text-[color:var(--color-fg)]">{host.name}</span>
                  <span class="type-meta mt-0.5 block truncate text-[color:var(--color-fg-muted)]">{host.url}</span>
                </span>
                {#if host.id === hostId}<span class="type-meta text-[color:var(--color-accent)]">selected</span>{/if}
              </ActionRow>
            {:else}
              <div class="type-copy px-3 py-3 text-[color:var(--color-fg-muted)]">no hosts connected</div>
            {/each}
          </div>
        </div>

        <label class="block">
          <div class="label mb-1.5">cwd</div>
          <Button
            type="button"
            variant="outline"
            disabled={!hostId}
            onclick={() => (pickerOpen = true)}
            class="h-auto w-full justify-start gap-2 rounded-[var(--radius-md)] border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-3 py-2.5 text-left active:bg-[color:var(--color-surface-2)]"
          >
            <Folder class="size-3.5 shrink-0 text-[color:var(--color-fg-muted)]" />
            {#if cwd}
              <span class="type-copy min-w-0 flex-1 truncate">{cwd}</span>
            {:else}
              <span class="type-copy text-[color:var(--color-fg-muted)]">choose a directory…</span>
            {/if}
          </Button>
        </label>

        <div>
          <label class="label mb-1.5 block" for="session_title">title</label>
          <Input id="session_title" type="text" bind:value={title} placeholder={cwd ? basename(cwd) : "session title"} class="h-10" />
        </div>

      </div>

      <div class="px-3 pt-2">
        <Button type="button" disabled={!canCreate} class="h-10 w-full" onclick={handleCreate}>
          <Plus class="size-3.5" />
          {creating ? "creating…" : "create session"}
        </Button>
      </div>
    {/if}
  </Sheet.BottomContent>
</Sheet.Root>
