// pi-mobile/src/features/chat/actions/SessionInfoView.tsx
import { Show, createResource } from "solid-js";
import { Download } from "lucide-solid";
import { getSessionStats, sessionExportHtmlUrl } from "@/lib/api";
import { getBridgeUrl } from "@/lib/settings";
import { formatCost, formatTokens } from "@/lib/format";
import { InfoRow } from "./shared";

function formatContextPercent(percent: number | null): string {
  return percent === null ? "" : ` · ${Math.round(percent)}%`;
}

export default function SessionInfoView(props: { sessionId: string }) {
  const [stats] = createResource(async () => {
    const baseUrl = await getBridgeUrl();
    return getSessionStats(baseUrl, props.sessionId);
  });

  async function downloadHtmlExport() {
    const baseUrl = await getBridgeUrl();
    const a = document.createElement("a");
    a.href = sessionExportHtmlUrl(baseUrl, props.sessionId);
    a.download = `pi-session-${props.sessionId}.html`;
    a.rel = "noreferrer";
    document.body.append(a);
    a.click();
    a.remove();
  }
  return (
    <div class="flex-1 overflow-y-auto px-3 py-3">
      <Show when={stats.loading}><div class="text-[12px] text-[color:var(--color-fg-faint)]">loading session info…</div></Show>
      <Show when={stats()}>
        {(s) => (
          <div class="space-y-2 text-[12px]">
            <InfoRow label="session id" value={s().sessionId} />
            <InfoRow label="file" value={s().sessionFile ?? "ephemeral"} />
            <InfoRow label="messages" value={String(s().totalMessages)} />
            <InfoRow label="user / assistant" value={`${s().userMessages} / ${s().assistantMessages}`} />
            <InfoRow label="tools" value={`${s().toolCalls} calls · ${s().toolResults} results`} />
            <InfoRow label="tokens" value={`${formatTokens(s().tokens.total)} total · ${formatTokens(s().tokens.input)} in · ${formatTokens(s().tokens.output)} out`} />
            <InfoRow label="cache" value={`${formatTokens(s().tokens.cacheRead)} read · ${formatTokens(s().tokens.cacheWrite)} write`} />
            <InfoRow label="cost" value={formatCost(s().cost)} />
            <Show when={s().contextUsage?.tokens !== null ? s().contextUsage : null}>
              {(c) => (
                <InfoRow
                  label="context"
                  value={`${formatTokens(c().tokens!)} / ${formatTokens(c().contextWindow)}${formatContextPercent(c().percent)}`}
                />
              )}
            </Show>
            <button
              type="button"
              onClick={downloadHtmlExport}
              class="flex h-10 w-full items-center justify-center gap-2 rounded-[var(--radius-md)] border border-[color:var(--color-border-strong)] text-[12px] font-medium active:bg-[color:var(--color-surface)]"
            >
              <Download size={14} />
              download HTML export
            </button>
          </div>
        )}
      </Show>
    </div>
  );
}

// pi-mobile/src/features/chat/actions/SessionInfoView.svelte
<script lang="ts">
  import { Download } from "@lucide/svelte";
  import type { SessionStats } from "@pi-mobile/protocol";
  import { getSessionStats, sessionExportHtmlUrl } from "@/features/chat/api";
  import { formatCost, formatTokens } from "@/shared/lib/format";

  let { sessionId }: { sessionId: string } = $props();

  let stats = $state<SessionStats | null>(null);
  let loading = $state(false);
  let error = $state<string | null>(null);

  $effect(() => {
    void loadStats();
  });

  async function loadStats(): Promise<void> {
    loading = true;
    error = null;
    try {
      stats = await getSessionStats(sessionId);
    } catch (caught) {
      error = String(caught);
    } finally {
      loading = false;
    }
  }

  function formatContextPercent(percent: number | null): string {
    return percent === null ? "" : ` · ${Math.round(percent)}%`;
  }

  function downloadHtmlExport(): void {
    const anchor = document.createElement("a");
    anchor.href = sessionExportHtmlUrl(sessionId);
    anchor.download = `pi-session-${sessionId}.html`;
    anchor.rel = "noreferrer";
    document.body.append(anchor);
    anchor.click();
    anchor.remove();
  }
</script>

<div class="flex-1 overflow-y-auto px-3 py-3">
  {#if loading}<div class="text-[12px] text-[color:var(--color-fg-faint)]">loading session info…</div>{/if}
  {#if error}<div class="text-[12px] text-[color:var(--color-danger)]">{error}</div>{/if}
  {#if stats}
    <div class="space-y-2 text-[12px]">
      {@render InfoRow("session id", stats.sessionId)}
      {@render InfoRow("file", stats.sessionFile ?? "ephemeral")}
      {@render InfoRow("messages", String(stats.totalMessages))}
      {@render InfoRow("user / assistant", `${stats.userMessages} / ${stats.assistantMessages}`)}
      {@render InfoRow("tools", `${stats.toolCalls} calls · ${stats.toolResults} results`)}
      {@render InfoRow("tokens", `${formatTokens(stats.tokens.total)} total · ${formatTokens(stats.tokens.input)} in · ${formatTokens(stats.tokens.output)} out`)}
      {@render InfoRow("cache", `${formatTokens(stats.tokens.cacheRead)} read · ${formatTokens(stats.tokens.cacheWrite)} write`)}
      {@render InfoRow("cost", formatCost(stats.cost))}
      {#if stats.contextUsage?.tokens !== null && stats.contextUsage}
        {@render InfoRow("context", `${formatTokens(stats.contextUsage.tokens!)} / ${formatTokens(stats.contextUsage.contextWindow)}${formatContextPercent(stats.contextUsage.percent)}`)}
      {/if}
      <button type="button" onclick={downloadHtmlExport} class="flex h-10 w-full items-center justify-center gap-2 rounded-[var(--radius-md)] border border-[color:var(--color-border-strong)] text-[12px] font-medium active:bg-[color:var(--color-surface)]">
        <Download class="size-3.5" />
        download HTML export
      </button>
    </div>
  {/if}
</div>

{#snippet InfoRow(label: string, value: string)}
  <div class="rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-3 py-2">
    <div class="label">{label}</div>
    <div class="mt-1 break-words text-[12px] text-[color:var(--color-fg)]">{value}</div>
  </div>
{/snippet}
