// pi-mobile/src/features/chat/actions/SessionSettingsView.tsx
import { Show, createResource, createSignal } from "solid-js";
import type { QueueMode, SessionSettings, ThinkingLevel } from "@pi-mobile/protocol";

const THINKING_LEVELS = ["off", "low", "medium", "high"] as const satisfies readonly ThinkingLevel[];
const QUEUE_MODES = ["one-at-a-time", "all"] as const satisfies readonly QueueMode[];
import { getSessionSettings, patchSessionSettings } from "@/lib/api";
import { getBridgeUrl } from "@/lib/settings";
import { haptic } from "@/lib/haptics";
import { Segmented, ToggleRow } from "./shared";
import type { ActionErrorHandler } from "./types";

export default function SessionSettingsView(props: { sessionId: string; onError: ActionErrorHandler }) {
  const [saving, setSaving] = createSignal<string | null>(null);
  const [settings, { refetch, mutate }] = createResource(async () => {
    const baseUrl = await getBridgeUrl();
    return getSessionSettings(baseUrl, props.sessionId);
  });

  async function patch(key: keyof SessionSettings, value: ThinkingLevel | QueueMode | boolean) {
    if (saving()) return;
    setSaving(String(key));
    props.onError(null);
    try {
      const baseUrl = await getBridgeUrl();
      const next = await patchSessionSettings(baseUrl, props.sessionId, { [key]: value });
      mutate(next);
      haptic.success();
    } catch (e) {
      props.onError(String(e));
      await refetch();
    } finally {
      setSaving(null);
    }
  }

  return (
    <div class="flex-1 overflow-y-auto px-3 py-3">
      <Show when={settings.loading}><div class="text-[12px] text-[color:var(--color-fg-faint)]">loading settings…</div></Show>
      <Show when={settings()}>
        {(s) => (
          <div class="space-y-4">
            <Segmented label="thinking level" options={s().availableThinkingLevels.length ? s().availableThinkingLevels : THINKING_LEVELS} value={s().thinkingLevel} disabled={saving() !== null} onChange={(v) => patch("thinkingLevel", v)} />
            <Segmented label="steering while running" options={QUEUE_MODES} value={s().steeringMode} disabled={saving() !== null} onChange={(v) => patch("steeringMode", v)} />
            <Segmented label="follow-up delivery" options={QUEUE_MODES} value={s().followUpMode} disabled={saving() !== null} onChange={(v) => patch("followUpMode", v)} />
            <ToggleRow label="auto compact" checked={s().autoCompaction} disabled={saving() !== null} onChange={(v) => patch("autoCompaction", v)} />
            <ToggleRow label="auto retry" checked={s().autoRetry} disabled={saving() !== null} onChange={(v) => patch("autoRetry", v)} />
          </div>
        )}
      </Show>
    </div>
  );
}

// pi-mobile/src/features/chat/actions/SessionSettingsView.svelte
<script lang="ts">
  import type { SessionControl, SessionControls } from "@pi-mobile/protocol";
  import type { ActionErrorHandler } from "./types";
  import { getSessionSettings, patchSessionSetting } from "@/features/chat/api";
  import { haptics } from "@/shared/mobile/haptics";

  let {
    sessionId,
    onError,
    filterKeys,
  }: {
    sessionId: string;
    onError: ActionErrorHandler;
    filterKeys?: readonly string[];
  } = $props();

  let saving = $state<string | null>(null);
  let settings = $state<SessionControls | null>(null);
  let loading = $state(false);

  const visibleControls = $derived((settings?.controls ?? []).filter((control: SessionControl) => !filterKeys || filterKeys.includes(control.key)));

  $effect(() => {
    void loadSettings();
  });

  async function loadSettings(): Promise<void> {
    loading = true;
    try {
      settings = await getSessionSettings(sessionId);
    } catch (error) {
      onError(String(error));
    } finally {
      loading = false;
    }
  }

  async function patch(key: string, value: string | boolean): Promise<void> {
    if (saving) return;
    const previous = settings;
    saving = key;
    onError(null);
    if (previous) settings = patchLocal(previous, key, value);
    try {
      settings = await patchSessionSetting(sessionId, key, value);
      haptics.success();
    } catch (error) {
      onError(String(error));
      settings = previous;
      await loadSettings();
    } finally {
      saving = null;
    }
  }

  function patchLocal(source: SessionControls, key: string, value: string | boolean): SessionControls {
    return {
      ...source,
      controls: source.controls.map((control: SessionControl) => {
        if (control.key !== key) return control;
        if (control.kind === "select" && typeof value === "string") return { ...control, value };
        if (control.kind === "boolean" && typeof value === "boolean") return { ...control, value };
        return control;
      }),
    };
  }
</script>

<div class="flex-1 overflow-y-auto px-3 py-3">
  {#if loading}<div class="text-[12px] text-[color:var(--color-fg-faint)]">loading settings…</div>{/if}
  {#if settings}
    <div class="space-y-4">
      {#each visibleControls as control (control.key)}
        {@render Control(control, saving === control.key, (value) => patch(control.key, value))}
      {/each}
    </div>
  {/if}
</div>

{#snippet Control(control: SessionControl, isSaving: boolean, onChange: (value: string | boolean) => void)}
  {#if control.kind === "select"}
    {#if control.options.length <= 4 && control.options.every((option: { description?: string }) => !option.description)}
      {@render Segmented(control.label, control.options, control.value, isSaving, onChange)}
    {:else}
      {@render SelectRows(control.label, control.options, control.value, isSaving, onChange)}
    {/if}
  {:else if control.kind === "boolean"}
    {@render ToggleRow(control.label, control.value, isSaving, onChange)}
  {/if}
{/snippet}

{#snippet ToggleRow(label: string, checked: boolean, disabled: boolean, onChange: (checked: boolean) => void)}
  <button type="button" disabled={disabled} onclick={() => onChange(!checked)} class="flex w-full items-center justify-between rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)] px-3 py-3 text-left active:bg-[color:var(--color-surface-2)] disabled:opacity-70">
    <span class="text-[12.5px] font-medium">{label}</span>
    <span class={checked ? "text-[12px] text-[color:var(--color-accent)]" : "text-[12px] text-[color:var(--color-fg-faint)]"}>{checked ? "on" : "off"}</span>
  </button>
{/snippet}

{#snippet Segmented(label: string, options: readonly { value: string; label: string; description?: string; disabled?: boolean }[], value: string, disabled: boolean, onChange: (value: string) => void)}
  <div>
    <div class="label mb-1.5">{label}</div>
    <div class="grid grid-cols-2 gap-1 rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-bg)] p-1">
      {#each options as option (option.value)}
        <button type="button" disabled={disabled || option.disabled || option.value === value} onclick={() => onChange(option.value)} class={option.value === value ? "rounded-[var(--radius-sm)] bg-[color:var(--color-accent)] px-2 py-2 text-[11px] font-medium text-[color:var(--color-bg)]" : "rounded-[var(--radius-sm)] px-2 py-2 text-[11px] text-[color:var(--color-fg-muted)] active:bg-[color:var(--color-surface)] disabled:opacity-70"}>
          {option.label}
        </button>
      {/each}
    </div>
  </div>
{/snippet}

{#snippet SelectRows(label: string, options: readonly { value: string; label: string; description?: string; disabled?: boolean }[], value: string, disabled: boolean, onChange: (value: string) => void)}
  <div>
    <div class="label mb-1.5">{label}</div>
    <div class="overflow-hidden rounded-[var(--radius-md)] border border-[color:var(--color-border)] bg-[color:var(--color-surface)]">
      {#each options as option (option.value)}
        <button type="button" disabled={disabled || option.disabled || option.value === value} onclick={() => onChange(option.value)} class="hairline-b flex w-full items-center gap-3 px-3 py-2.5 text-left active:bg-[color:var(--color-surface-2)] disabled:opacity-70">
          <span class="min-w-0 flex-1">
            <span class="block truncate text-[12.5px] text-[color:var(--color-fg)]">{option.label}</span>
            {#if option.description}<span class="mt-0.5 block truncate text-[10.5px] text-[color:var(--color-fg-faint)]">{option.description}</span>{/if}
          </span>
          {#if option.value === value}<span class="text-[12px] text-[color:var(--color-accent)]">selected</span>{/if}
        </button>
      {/each}
    </div>
  </div>
{/snippet}
