// pi-mobile/src/features/sessions/components/SessionActions.svelte
<script lang="ts">
  import { Archive, ArchiveRestore, Pencil, Trash2 } from "@lucide/svelte";
  import type { SessionMeta } from "@pi-mobile/protocol";
  import { Button } from "@/shared/ui/button";
  import * as DropdownMenu from "@/shared/ui/dropdown-menu";

  let {
    session,
    onRename,
    onToggleArchive,
    onDelete,
  }: {
    session: SessionMeta;
    onRename: (session: SessionMeta) => void;
    onToggleArchive: (session: SessionMeta) => void;
    onDelete: (session: SessionMeta) => void;
  } = $props();
</script>

<DropdownMenu.Root>
  <DropdownMenu.Trigger>
    {#snippet child({ props })}
      <Button type="button" variant="ghost" size="icon-sm" aria-label="Session actions" {...props}>⋯</Button>
    {/snippet}
  </DropdownMenu.Trigger>
  <DropdownMenu.Content align="end" class="min-w-40">
    <DropdownMenu.Item onclick={() => onRename(session)}>
      <Pencil class="size-3.5" />
      rename
    </DropdownMenu.Item>
    <DropdownMenu.Item onclick={() => onToggleArchive(session)}>
      {#if session.archived}
        <ArchiveRestore class="size-3.5" />
        unarchive
      {:else}
        <Archive class="size-3.5" />
        archive
      {/if}
    </DropdownMenu.Item>
    <DropdownMenu.Item onclick={() => onDelete(session)} class="text-[color:var(--color-danger)]">
      <Trash2 class="size-3.5" />
      delete
    </DropdownMenu.Item>
  </DropdownMenu.Content>
</DropdownMenu.Root>

// pi-mobile/src/features/sessions/components/SessionActions.tsx
import { Show } from "solid-js";
import { Pencil, Archive, Trash2, ArchiveRestore } from "lucide-solid";
import type { SessionMeta } from "@pi-mobile/protocol";
import BottomSheet from "@/components/BottomSheet";
import { Button } from "@/components/ui/button";

export default function SessionActions(props: {
  session: SessionMeta | null;
  onRename: () => void;
  onToggleArchive: () => void;
  onDelete: () => void;
  onClose: () => void;
}) {
  return (
    <Show when={props.session}>
      {(s) => (
        <BottomSheet open title={<span class="truncate">{s().title}</span>} onClose={props.onClose}>
          <Button
            type="button"
            variant="plain"
            onClick={props.onRename}
            class="hairline-b h-auto w-full justify-start gap-3 px-3 py-3 text-left text-[color:var(--color-fg)] active:bg-[color:var(--color-surface)]"
          >
            <Pencil size={14} class="text-[color:var(--color-fg-muted)]" />
            <span class="text-[13px]">Rename</span>
          </Button>

          <Button
            type="button"
            variant="plain"
            onClick={props.onToggleArchive}
            class="hairline-b h-auto w-full justify-start gap-3 px-3 py-3 text-left text-[color:var(--color-fg)] active:bg-[color:var(--color-surface)]"
          >
            <Show
              when={s().archived}
              fallback={
                <>
                  <Archive size={14} class="text-[color:var(--color-fg-muted)]" />
                  <span class="text-[13px]">Archive</span>
                </>
              }
            >
              <ArchiveRestore size={14} class="text-[color:var(--color-fg-muted)]" />
              <span class="text-[13px]">Restore from archive</span>
            </Show>
          </Button>

          <Button
            type="button"
            variant="plain"
            onClick={props.onDelete}
            class="h-auto w-full justify-start gap-3 px-3 py-3 text-left text-[color:var(--color-danger)] active:bg-[color:var(--color-surface)]"
          >
            <Trash2 size={14} />
            <span class="text-[13px]">Delete</span>
          </Button>
        </BottomSheet>
      )}
    </Show>
  );
}
